

import { ReactNode } from "react";
import Chat from "@components/Chat";
import Providers from '@components/Providers';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}


export default function BotskiLayout({ children }: { children: ReactNode }) {


    return (
        <>
            <Providers>
                <div className={inter.className}>
                    <Chat />
                    {children}
                </div>
            </Providers>
        </>
    );
}





// If loading a variable font, you don't need to specify the font weight
// const oswald = Oswald({ subsets: ['latin'], variable: '--font-oswald', display: 'swap' })
// const roboto_mono = Roboto_Mono({ subsets: ['latin'], variable: '--font-roboto-mono', display: 'swap' });


